### ISSUE TITLE
array slice + array repetition

### ISSUE THREAD

**Issue by jedilando** [satyr/coco#147]
> # example1.co
> 
> [x[a], x[b]]*2

compiles correctly into

> # example1.js
> 
> var __ref, __ref1;
> [__ref = x[a], __ref1 = x[b], __ref, __ref1];

but

> # example2.co
> 
> x[a, b]*2

compiles into

> # example2.js
> 
> [x[a], x[b]] \* 2;

As far as I understand example2.co should compile into example1.js

Coco 0.7.5
Windows XP

**Comment by satyr** [comment]
This was intentional (the [additions](https://github.com/satyr/coco/wiki/additions) currently says the left operand needs to be a literal) because correctly deducing the operand type is impossible in complex/dynamic cases.

Though seeing that string repetition does deduce to some extent and unary spread works on array slice, making this work probably doesn't hurt.

```
$ coco -bce '(x + "" + y) * 2'
var __ref;
(__ref = x + "" + y) + __ref;

$ coco -bce '+x[a, b]'
+x[a], +x[b];
```

**Comment by jedilando** [comment]
Ok, thanks for answer!
