### ISSUE TITLE
quick maps makes later IN unrecognized

### ISSUE THREAD

**Issue by vendethiel** [satyr/coco#195]
`coco -le "for a then b; a in b"`
`NEWLINE:\n ID:a THEN ID:b NEWLINE:; ID:a IN ID:b NEWLINE:\n`

probably because @seenFor doesn't change

gkz/LiveScript#245

**Comment by satyr** [comment]
Ow.

**Comment by vendethiel** [comment]
Note that you have no further problem with that because you didn't enabled quick-post-`for`. was that intentional ?

**Comment by satyr** [comment]
Yes, it's parsed differently from other loops, being a complement of the proposed `*.` operator and a variant of `with`.

E.g. you can directly dot-access it:

```
for [0 1 2]
  &*3
.concat 4 5
```

**Comment by vendethiel** [comment]
Yes, this is really nice. Thought I could go a bit further tho.

``` coffee
for [0 1 2]
  &*3
|> &length
```

**Comment by goto-bus-stop** [comment]
This can get pretty nasty, eg in [this toml parser](https://github.com/renekooi/toml-coco/blob/master/toml.co).
Took quite some time to figure out why line ~100 was erroring, but it appeared to be caused by the `for key =>` on line ~50. The solution was to put the `of` test in a new function and place it above line 50 (on line 43, to be precise), but it's a rather expensive error if you don't know what might be causing it :s

**Comment by satyr** [comment]
Sorry about that. Will soon release 0.9.1 with the fix.
