### ISSUE TITLE
implicitly braced object and function call

### ISSUE THREAD

**Issue by adrusi** [satyr/coco#62]
I wrote a class library that supports private members that can be inherited, but in order to make them I need to use curly braces.

I would expect

```
Foo = Class
  initialize: ->
    console.log @$private.greeting

  private:
    greeting: \hi
```

to compile to

```
var Foo;
Foo = Class({
  initialize: function() {
    console.log(this.$private.greeting);
  },
  private: {
    greeting: "hi"
  }
});
```

But instead I get:

```
var Foo;
Foo = Class;
({
  initialize: function() {
    console.log(this.$private.greeting);
  },
  private: {
    greeting: "hi"
  }
});
```

I don't think there's any use just having an object that isn't ever interacted with in any way, so this seems to be a real bug.

**Comment by satyr** [comment]
Coco uses `do` block for this, instead of specialcasing "block that starts with an implicit object" (to avoid inconsistencies like [coffee#981](https://github.com/jashkenas/coffee-script/issues/981)).

```
Foo = Class do
  initialize: ->
```

> I don't think there's any use just having an object that isn't ever interacted with in any way

Bare blocks are equivalent to lines of expressions, to support cases like

```
$ coco -bps
[ a
  b ]

[a, b];

$ coco -ts
[ a
  b ]

[ ID:a
INDENT:2 ID:b DEDENT:2 ]

TERMINATOR:\n
```

Notice that `b` is in its own block.
