### ISSUE TITLE
inconsistent range keywords "from" and "to"

### ISSUE THREAD

**Issue by benwbooth** [satyr/coco#67]
Currently, the syntax for specifying a range starting from 0 in a for loop is:
`i for i from 3`

Output: 
`[ 0, 1, 2 ]`

I think it could be more intuitively written this way:
`i for i til 3`

`from` should specify the starting value, and `til` or `to` should specify the ending value. If `from` is omitted, it should default to zero. This would be more consistent with specifying a start and stop value:
`i for i from 0 til 3`

**Comment by satyr** [comment]
This `from N` sugar originates from `range N` of Python/Clojure etc., where the shorthand notation specifies the _end_ part rather than _start_. I agree that it can feel a little strange English-wise.

> `i for i til 3`

I like it. Though a little challenging lexing-wise (`to`/`til` is contextual to `from` right now).
